name: Build RasFocus Pro

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4  # এখানে v3 থেকে v4 করা হয়েছে

    - name: Build Project using CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # এখানে v3 থেকে v4 করা হয়েছে
      with:
        name: RasFocus_Pro_App
        path: build\Release\RasFocus_Pro.exe
